name: test_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
hive_generator: ^1.1.0
build_runner: ^2.0.5

flutter:
  uses-material-design: true

assets:
- assets/decision_map.csv

